# Live Staging Theme
development:
  password: ${DEV_PASSWD}
  theme_id: ${DEV_THEMEID}
  store: ${DEV_SHOP}
  directory: views
  ignore_files:
    - config/settings_data.json
    - .env
    - templates/*
    - locales/*

# Development environment
prod-a:
  password: ${PROD_A_PASSWD}
  theme_id: ${PROD_A_THEMEID}
  store: ${PROD_A_SHOP}
  # directory: views
  ignore_files:
    # - config/settings_data.json
    - .env
    # - templates/*
    - locales/*

# Production environment
<<<<<<< HEAD
production:
  password: ${PROD_A_PASSWD}
  theme_id: ${PROD_A_THEMEID}
  store: ${PROD_A_SHOP}
=======
prod-b:
  password: ${PROD_B_PASSWD}
  theme_id: ${PROD_B_THEMEID}
  store: ${PROD_B_SHOP}
>>>>>>> production-a
  # directory: views
  ignore_files:
    # - config/settings_data.json
    - .env
    # - templates/*
    - locales/*